# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/grandprimevelte/setup-makefiles.sh

# Graphics
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libEGL_MRVL.so:system/vendor/lib/egl/libEGL_MRVL.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libGLESv1_CM_MRVL.so:system/vendor/lib/egl/libGLESv1_CM_MRVL.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libGLESv2_MRVL.so:system/vendor/lib/egl/libGLESv2_MRVL.so
